メンバーリストの更新
approvers/approvers.github.io pull request #130
Opened 2020-11-25 16:03 UTC by MikuroXina

- Add ぐうたら

2020-11-25 16:36 UTC, siketyan approved these changes

2020-11-25 16:36 UTC, siketyan requested changes

2020-11-25 16:36 UTC, siketyan commented on data/members/list.yaml
> +      link: https://twitter.com/guutara_nonki
```suggestion
      url: https://twitter.com/guutara_nonki
```

2020-11-26 00:23 UTC, siketyan approved these changes

2020-11-27 05:23 UTC, unios103 approved these changes

2020-11-27 05:23 UTC, merged