ci(gh-actions): improve ci
approvers/approvers.github.io pull request #143
Opened 2020-12-20 15:21 UTC by shun-shobon

- CIのファイルを一つにまとめました。
- Pull Requestを作成した際のトリガーを削除しました。
- lintのjobを一つにまとめました。
- いくつかの依存していたActionをアップグレードしました。

2020-12-20 15:40 UTC, MikuroXina approved these changes

2020-12-25 07:32 UTC, siketyan requested changes
README.md のバッジも編集してください 🙏

2020-12-25 07:35 UTC, siketyan approved these changes

2020-12-25 07:35 UTC, MikuroXina approved these changes

2020-12-25 07:37 UTC, merged