CI に Next.js のキャッシュを追加
approvers/approvers.github.io pull request #84
Opened 2020-10-08 23:18 UTC by MikuroXina

なんか CI のコンソールに警告が出てたので

2020-10-08 23:25 UTC, shun-shobon approved these changes

2020-10-09 03:58 UTC, siketyan requested changes
この glob は危険では

2020-10-09 03:58 UTC, siketyan commented on .github/workflows/test.yml
> +          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
```suggestion
          key: ${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}
```

2020-10-09 12:25 UTC, siketyan approved these changes

2020-10-10 02:51 UTC, shun-shobon approved these changes

2020-10-10 02:52 UTC, merged