Redesign
approvers/approvers.github.io pull request #98
Opened 2020-10-16 10:07 UTC by unios103

色などを変更しました。
画面要素・構成はほとんど変わっていません。

<img width="986" alt="Screen Shot 2020-10-16 at 2 06 38" src="https://user-images.githubusercontent.com/55628112/96162989-3bcea500-0f54-11eb-9d4b-626eaed8ee51.png">

2020-10-16 15:29 UTC, MikuroXina requested changes

2020-10-16 15:29 UTC, MikuroXina commented on src/scss/_details.variable.scss
> +$light: #fff;
グローバルな変数として色を保持するのは `_details` ではなく `_color` だと思います

2020-10-16 15:35 UTC, unios103 commented on src/scss/_details.variable.scss
> +$light: #fff;
~~（color.get-main-color("main")って書くのを面倒くさがったせいなので）~~ [pull/100](https://github.com/approvers/approvers.github.io/pull/100) がマージされ次第修正します...

2020-12-13 15:12 UTC, mirror-kt commented
@unios103 any news of this?

2020-12-19 11:34 UTC, closed without merging

2020-12-19 11:36 UTC, MikuroXina commented
link ブランチから生えていたため, update/design というブランチ名で dev ブランチから生やし直しました.